source "$HOME/.zsh/beauty.zsh"
source "$HOME/.zsh/plugins.zsh"
source "$HOME/.zsh/export.zsh"
source "$HOME/.zsh/theme.zsh" 
source "$HOME/.zsh/alias.zsh"
source "$HOME/.zsh/keymap.zsh"
source "$HOME/.zsh/plugins/vi.zsh"
source "$HOME/.zsh/func_init.zsh"
